#!/usr/bin/env python3
"""Build the paste-in prompts for platforms that have no skills directory.

Each paste file is `instructions.md` plus one flow, concatenated. The flows are
the same files the Claude skill runs, so a calibration change to a step lands on
both platforms from one edit.

    python3 marketing-workshop/portable/build.py          # write paste/
    python3 marketing-workshop/portable/build.py --check  # verify, change nothing
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL = HERE.parent
FLOWS = ["positioning", "copy", "distribution"]

# The GPT builder's Instructions box. Projects and pasted prompts are roomier,
# but this is the tightest place instructions.md has to fit.
GPT_INSTRUCTION_LIMIT = 8000

# Flow text must not name a path — it has to read the same on a platform with no
# filesystem. Storage mapping belongs in SKILL.md or instructions.md.
PATH_MARKERS = ["brand-brief.md", "copy/", "tasks/", "flows/"]

BANNER = """<!-- Generated by portable/build.py — do not edit.
     Edit ../flows/{flow}.md or ../portable/instructions.md and rebuild. -->

*Paste this whole file into a new chat as your first message, then answer the
first question it asks. Bring your brief with you if you have one.*

"""


def build(flow):
    instructions = (HERE / "instructions.md").read_text()
    body = (SKILL / "flows" / f"{flow}.md").read_text()
    return BANNER.format(flow=flow) + instructions.rstrip() + "\n\n---\n\n" + body


def main():
    check = "--check" in sys.argv
    problems = []

    size = len((HERE / "instructions.md").read_text())
    status = "ok" if size <= GPT_INSTRUCTION_LIMIT else "OVER LIMIT"
    print(f"instructions.md  {size:>6} chars  (limit {GPT_INSTRUCTION_LIMIT}) {status}")
    if size > GPT_INSTRUCTION_LIMIT:
        problems.append(f"instructions.md is {size - GPT_INSTRUCTION_LIMIT} chars over the GPT builder limit")

    for flow in FLOWS:
        text = (SKILL / "flows" / f"{flow}.md").read_text()
        for marker in PATH_MARKERS:
            if marker in text:
                problems.append(f"flows/{flow}.md names a path ({marker}) — flows stay platform-neutral")

        out = SKILL / "portable" / "paste" / f"{flow}.md"
        built = build(flow)
        if check:
            if not out.exists() or out.read_text() != built:
                problems.append(f"portable/paste/{flow}.md is stale — rerun build.py")
        else:
            out.write_text(built)
        print(f"paste/{flow}.md{'':<{max(0, 10 - len(flow))}} {len(built):>6} chars")

    for p in problems:
        print(f"  ! {p}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
